Update Czech aerodrome frequencies
XCSoar/xcsoar-data-content pull request #136
Opened 2021-03-30 21:40 UTC by DanD222

LKCE 122.140 (formerly 123.590)
LKCB 120.260 (formerly 122.205)
LKPI 125.610 (formerly 123.610)

source: 
https%3A%2F%2Faim.rlp.cz%2Fcz%2FprezentaceGA2021%2F06_SeminarGA2021_MD_Topkova_Pustina_Kmitocty_v_prvnim_leteckem_pasmu_a_novela_ZCL.pptx&amp;usg=AOvVaw1cYHxFsjjsY6Z5bOA-1GqJ

2021-03-31 11:21 UTC, jharting requested changes

2021-03-31 11:21 UTC, jharting commented on waypoints/Czech_Republic.cup
> +"CHEB","LKCB",CZ,5003.983N,01224.767E,483.0m,5,60,1400.0m,120.260,"Cheb, ULL"
VFR Manual says it should be `120.610`

https://aim.rlp.cz/vfrmanual/actual/lkcb_text_cz.html

2021-04-01 06:27 UTC, DanD222 commented on waypoints/Czech_Republic.cup
> +"CHEB","LKCB",CZ,5003.983N,01224.767E,483.0m,5,60,1400.0m,120.260,"Cheb, ULL"
Good catch, thanks - let's use that.

2021-04-01 07:03 UTC, jharting approved these changes

2021-04-01 19:22 UTC, merged