Update USA_PG_REG9-12.cup
XCSoar/xcsoar-data-content pull request #220
Opened 2022-03-15 00:28 UTC by ventus99

add Texas Soaring and Kansas waypoints and tasks

# The purpose of this change

# The source of the data (for e.g. new frequencies)

2022-03-15 10:08 UTC, lordfolken requested changes

2022-03-15 10:08 UTC, lordfolken commented on data/content/waypoint/region/USA_PG_REG9-12.cup
> +"TexasSA Roundabout CCW","???","Tsa Gld","Sanders Estes Unit","Double A","Ridge Creek","RV Storage","Tsa Gld","???"
"???" is a value, Shortnames are parsed. If there is no value intended use ""

2022-03-15 10:11 UTC, lordfolken commented on data/content/waypoint/region/USA_PG_REG9-12.cup
> +Pinal Airpark,071PINAL,US,3230.583N,11119.517W,577.0m,5,134,2087.6m,123.05,Pinal Airprk MZJ123.050 AWOS:130.375 RY 12/30:6849x99MGR: SAMUEL SORIA|520-682-4181|(520) 682-4181 X5755
I would quote the comment field "Pinal Airprk..." its just safer.

2022-03-15 10:11 UTC, lordfolken commented on data/content/waypoint/region/USA_PG_REG9-12.cup
> +Pinal Airpark,071PINAL,US,3230.583N,11119.517W,577.0m,5,134,2087.6m,123.05,Pinal Airprk MZJ123.050 AWOS:130.375 RY 12/30:6849x99MGR: SAMUEL SORIA|520-682-4181|(520) 682-4181 X5755
There are several more instances, in general i would quote the comment field.

2022-03-15 16:51 UTC, ventus99 commented on data/content/waypoint/region/USA_PG_REG9-12.cup
> +"TexasSA Roundabout CCW","???","Tsa Gld","Sanders Estes Unit","Double A","Ridge Creek","RV Storage","Tsa Gld","???"
The "???" come from SeeYou, the people who create the .cup standard.  It leaves the takeoff and landing fields blank.  If they are left empty it could create a problem with some programs.

2022-03-16 01:38 UTC, ventus99 commented
I have made suggested changes

2022-03-17 13:26 UTC, lordfolken approved these changes

2022-03-17 13:27 UTC, merged