Update CZ.cup frequencies for 2022
XCSoar/xcsoar-data-content pull request #256
Opened 2022-05-24 21:53 UTC by DanD222

Differences identified in:
https://aim.rlp.cz/vfrmanual/actual/lkbrez_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkco_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkct_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkdk_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkhrad_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkjiri_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkkune_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkkv_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkleto_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lklt_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkmilo_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkmr_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkpd_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkpisk_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkpr_text_en.html
https://aim.rlp.cz/vfrmanual/actual/lkto_text_en.html

2022-05-24 22:06 UTC, lordfolken requested changes
Some formatting errors, which is why the check fails.

2022-05-24 22:06 UTC, lordfolken commented on data/content/waypoint/country/CZ.cup
> +"HRADCANY U MIMONE-P","LKHRAD”,CZ,5037.167N,01443.967E,278.0m,5,90,2700.0m,134.815,"Hradcany u Mimone, ULL Private"
"LKHRAD” <- the trailing " is a different format than the leading one.

2022-05-24 22:06 UTC, lordfolken commented on data/content/waypoint/country/CZ.cup
> +"PISEK","LKPISK",CZ,4920.367N,01406.833E,412.0m,5,160,600.0m,119,415,"Pisek, ULL"
The frequency field contains a , instead of a .

2022-05-31 17:09 UTC, DanD222 commented
@lordfolken Should be OK to merge now?

2022-05-31 17:23 UTC, lordfolken commented
The check is still failing.

2022-05-31 19:15 UTC, merged

2022-05-31 19:17 UTC, DanD222 commented
Thanks.. spotted the other quotation mark, missed the line ending :(