Delete country specific files and upload file for the world
XCSoar/xcsoar-data-content pull request #299
Opened 2022-11-22 22:12 UTC by ventus99

# Pull Request

## The purpose of this change
I originally split the files because XCSoar could not display more than 50 tasks in the file manager in one file.  The file is still very small so shouldn't make much difference in downloading.  Makes it easier for me to update the file.

## The source of the data (for e.g. new frequencies)

2022-12-02 13:29 UTC, lordfolken requested changes
I'm OK with the change in principal. The only thing: please name the file something Like CAN_USA_ProvingGroundsAll.cup Its otherwise difficult to understand what region is concerned.

2022-12-02 19:05 UTC, ventus99 commented
It includes Canada, USA, Netherlands, England, New Zealand right now.  I think we are expanding into Germany soon.  Should I name all of the countries included?  Or I could name it World_PG?

2022-12-07 08:29 UTC, ventus99 commented
I made the change to World_ProvingGrounds.  What do you think?

2022-12-24 22:34 UTC, lordfolken approved these changes

2022-12-24 22:34 UTC, merged